name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: python --version
    - name: Install
      run: pip install mkdocs
    - name: Deploy
      run: mkdocs build
